### ISSUE TITLE
unrelated to firedm: (sorry could only find this platform available)

### ISSUE THREAD

**Issue by Midnightmadwalk-coder** [afzl-wtu/firedm#1]
I saw a comment of yours regarding using unofficial Android 11 images for waydroid. Could you please share them? If you've any discord or telegram group, please do mention it. Thanks.

**Comment by afzl-wtu** [comment]
> I saw a comment of yours regarding using unofficial Android 11 images for waydroid. Could you please share them? If you've any discord or telegram group, please do mention it. Thanks.

No problem at all you can talk here

**Comment by afzl-wtu** [comment]
I followed all steps from this video for working android 11. https://youtu.be/6ib0A0hs7JM
I am not owner or anything to this channel.

**Comment by afzl-wtu** [comment]
You can find your link in this video description.
