### ISSUE TITLE
32 bit version?

### ISSUE THREAD

**Issue by Britooo09** [afzl-wtu/firedm#2]
Hey! I appreciate what you did. Do you have a file that works with 32 bit Windows? Thank you!

**Comment by afzl-wtu** [comment]
> Hey! I appreciate what you did. Do you have a file that works with 32 bit Windows? Thank you!

Sorry for late reply. I think for that you need to replace python and ffmpeg versions to 32 bit. It may be a difficult task. Moreover, no one use 32 bit versions.

**Comment by Britooo09** [comment]
> Moreover, no one use 32 bit versions.

Well, I think it's a pretty obvious thing, but people who don't have 64-bit systems DO use 32-bit versions (as is my case).
But thanks anyway. I've already found a better alternative.
