### ISSUE TITLE
Is FireDM 2022.2.5 still working?

### ISSUE THREAD

**Issue by altadr** [afzl-wtu/firedm#4]
Having used FireDM 2022.2.5 some months ago, 
(Win11, 64bit) I was very happy with this. 
Now trying again, seems it doesn't work anymore. 
How about you, does it still work for you?
Maybe only I made a mistake and FireDM 2022.2.5 is still ok. 
Or repairable?
Any help appreciated, 
Thank you very much!

**Comment by afzl-wtu** [comment]
Just update yt-dlp only

**Comment by afzl-wtu** [comment]
> Having used FireDM 2022.2.5 some months ago, (Win11, 64bit) I was very happy with this. Now trying again, seems it doesn't work anymore. How about you, does it still work for you? Maybe only I made a mistake and FireDM 2022.2.5 is still ok. Or repairable? Any help appreciated, Thank you very much!

Thanks for opening issue. I have updated yt-dlp in realeases. Please dowload it.
