### ISSUE TITLE
Not downloading youtube videos

### ISSUE THREAD

**Issue by DashReza7** [afzl-wtu/firedm#7]
I have it installed on my linux machine and it doesn't download youtube videos. It downloads the html webpage.

**Comment by afzl-wtu** [comment]
I know the issue. BTW you can only use yt-dlp command line for downloading videos from all supported website:
Just Download or install yt-dlp latest version and forget firedm.
```
yt-dlp -F "(link)" #Choose your desired video audio quality. I choose here 251 and 248 for example
yt-dlp -f 251+248 "(link)"
```

I will check if I can fix firedm.
